<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Les promesses / promise</title>
</head>
<body>
    <p>Les promesses sont des objets qui ont attraits à la notion d'asynchrone. <br>
    Le problème de l'asynchrone est que l'on se retrouve très souvent avec des call back, dans des call back, dans des call back, et ce code n'est pas pérenne pour le long terme</p>

    <script>
        // au niveau de son constructeur, les promesses attendent un paramètre qui sera une fonction qui aura 2 paramètres (resolve, reject) (en général on utilise ses noms pour ces 2 paramètres)
        const p = new Promise((resolve, reject) => {
            resolve(4)
            //reject(2)
        });
        console.log(p) 

        // pour savoir si la promesse a été résolu ou non. Pour cela, 2 méthodes ('then' si la promesse est résolue, qui prend en paramètre un call back qui sont les valeurs renvoyées lors de la résolution de la promesse ; et 'catch' si la promesse échoue)
        // que la promesse soit résolue ou échoue, 'finally' s'affiche tout le temps
        // p.then((n) => {
        //     console.log('Le nombre', n)
        // })

        // p.catch((e) => {
        //     console.log('Echec', e)
        // })

        // // OU
        // p
        //     .then((n) => {
        //         console.log('Le nombre', n)
        //     })
        //     .catch((e) => {
        //         console.log('Echec', e)
        //     })
        //     .finally(() => console.log('aaaa'))



    
        function wait(duration) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(duration)
                }, duration)
            })
        }

        function waitAndFail(duration) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    reject(duration)
                }, duration)
            })
        }

        // wait(2000)
        //     .then(() => {
        //         console.log('Attente 2s');
        //         return wait(1000)
        //     })
        //     .then(() => {
        //         console.log('Attente 1s');
        //         return waitAndFail(2000)
        //     })
        //     .catch((e) => {
        //         console.log('Echec', e)
        //     })

        // wait(2000)
        //     .then(() => {
        //         console.log('Attente 2s');
        //         return waitAndFail(1000)    // Uncaught (in promise) 1000       on a une promesse qui échoue et on n'a pas géré de 'catch' avec
        //     })
        //     .catch(() => null)

        
        async function main() {             // OU const main = async() => {}
            // return 4
            // throw new Error()
            await wait(2000)
            console.log('Bonjour')
            await wait(1000)
            console.log('Hello')
        }
        //console.log(main())
        main()
    </script>
</body>
</html>